### PR TITLE
fix: protocol claims DIKO rewards for liquidated vault

### PR DESCRIPTION
**Pull request by philipdesmedt**

### CODE REVIEW

**Comment by nieldeckx** [comment]
@philipdesmedt The vault rewards are already claimed by the protocol when vault is liquidated. But it is true that the vault will keep generating rewards during auction so we need to improve. We do need to keep "remove-collateral" as this makes sure to update vault-rewards. Without it, a liquidated vault will keep receiving rewards forever.

So I think we need to:
1) call remove-collateral so vault rewards stop
2) call claim-pending-rewards-liquidated-vault to get rewards

Can be done either when liquidation starts or ends.

**Comment by philipdesmedt** [comment]
@nieldeckx all right, makes sense, thx!

let's do it when liquidation starts - a vault's state is invalidated as soon as it has to be liquidated so the rewards from then on should go to the rest of the community.

**Comment by philipdesmedt** [comment]
@nieldeckx updated, something like this?

**Comment by nieldeckx** [comment]
@philipdesmedt added test to prove it's now working.

**Pull request merged**
